// Banque de 140 questions, construite à partir du contenu réel du Module 4
// (« La diffusion et distribution du documentaire »), fourni par le
// formateur : 19 documents de cours couvrant les séquences suivantes :
//   1. Diffusion, distribution, exploitation — vocabulaire de base
//   2. Diffuseurs TV
//   3. Plateformes numériques (SVOD/TVOD/AVOD/FVOD/FAST)
//   4. Le dossier de présentation type
//   5. Logline et synopsis
//   6. Note d'intention et note de réalisation
//   7. Le dossier de presse professionnel (EPK)
//   8. Évaluer les effets du documentaire sur le public
//   9. Analyser réception, controverses et points forts
//  10. Monter un plan de circulation du film
//  11. Savoir présenter son film aux bons interlocuteurs
//  12. Créer une bande-annonce qui donne envie
//  13. Déployer une communication cohérente
//  14. Articuler festivals, médias et projections
//  15. Préparer un film circulant sur plusieurs territoires
//  16. Défendre la valeur du film sans le dénaturer (négociation)
//  17. Activité de consolidation finale
//
// Chaque question a un id unique, un type, un texte, des options si QCM,
// une réponse correcte, et le nombre de points. Les questions sont
// formulées en mise en situation professionnelle plutôt qu'en rappel brut
// du cours, avec des exemples et scénarios inventés pour illustrer les
// notions (jamais les exemples ou cas nommés du cours lui-même), tout en
// restant fidèles au vocabulaire et aux concepts enseignés.
export const QUESTION_BANK = [
  // ============================================================
  // 1. Diffusion, distribution, exploitation — vocabulaire de base
  // ============================================================
  { id: "q001", type: "mcq", text: "Le producteur de votre film documentaire signe un contrat avec une société qui va préparer l'affiche, la bande-annonce et les contacts presse. Cette étape relève de :",
    options: ["La diffusion", "La distribution", "L'exploitation", "Le mandat"],
    answer: "La distribution", points: 1 },
  { id: "q002", type: "mcq", text: "Votre film est prévu en salle en France pendant 6 mois, puis à la télévision, puis sur une plateforme, pour une durée totale de 3 ans. Cette organisation dans le temps relève de :",
    options: ["La diffusion", "La distribution", "L'exploitation", "Le windowing"],
    answer: "L'exploitation", points: 2 },
  { id: "q003", type: "mcq", text: "Un dimanche soir, un spectateur regarde votre documentaire diffusé sur Arte. Ce moment concret relève de :",
    options: ["La diffusion", "La distribution", "L'exploitation", "Le mandat"],
    answer: "La diffusion", points: 1 },
  { id: "q004", type: "text", text: "Un contrat vous limite à vendre votre film uniquement en France et en Belgique. Quel mot désigne cette zone géographique où le contrat s'applique ?",
    answer: ["territoire"], points: 1 },
  { id: "q005", type: "mcq", text: "Un distributeur vous propose un contrat où lui seul aura le droit de montrer votre film en France pendant 3 ans. Comment appelle-t-on ce droit exclusif ?",
    options: ["Un territoire", "Une exclusivité", "Un holdback", "Un windowing"],
    answer: "Une exclusivité", points: 1 },
  { id: "q006", type: "text", text: "Un diffuseur vous impose qu'aucune exploitation VOD, SVOD ou AVOD ne pourra intervenir avant 18 mois après la sortie en salle, pour protéger son exclusivité. Comment appelle-t-on cette période d'interdiction ?",
    answer: ["holdback"], points: 2 },
  { id: "q007", type: "mcq", text: "Vous signez avec un distributeur un contrat qui lui donne le droit de faire circuler votre film. Comment s'appelle ce contrat ?",
    options: ["Un mandat de distribution", "Un droit moral", "Un master", "Une commission"],
    answer: "Un mandat de distribution", points: 1 },
  { id: "q008", type: "text", text: "Dans un mandat de distribution, votre société de production signe avec un distributeur qui obtient l'exploitation exclusive du film pour une durée de 4 ans. Après ces 4 ans, que se passe-t-il si aucune des deux parties ne demande de prolongation ?",
    answer: ["le contrat s'arrête", "le mandat prend fin", "le contrat s'arrête automatiquement", "fin du contrat", "il s'arrête"], points: 2 },
  { id: "q009", type: "text", text: "Le contrat mentionne les personnes ou sociétés qui possèdent les droits du film, comme l'auteur ou le producteur. Comment les appelle-t-on ?",
    answer: ["ayants droit", "ayants-droit", "les ayants droit"], points: 1 },

  // ============================================================
  // 2. Diffuseurs TV
  // ============================================================
  { id: "q010", type: "mcq", text: "Une chaîne de télévision impose ses propres règles techniques (format vidéo, son, sous-titres, générique) avant d'accepter de diffuser votre film. Comment appelle-t-on cette étape technique obligatoire ?",
    options: ["Le PAD", "La ligne éditoriale", "La case de programmation", "Le préachat"],
    answer: "Le PAD", points: 1 },
  { id: "q011", type: "mcq", text: "Une chaîne accepte de vous verser de l'argent avant même que votre film soit terminé, en échange du droit de le diffuser plus tard. Comment appelle-t-on cet accord ?",
    options: ["Un préachat", "Un mandat", "Un master", "Un holdback"],
    answer: "Un préachat", points: 1 },
  { id: "q012", type: "text", text: "Votre film est terminé artistiquement, mais la chaîne qui doit le diffuser vérifie encore le format vidéo, le son, les sous-titres et le générique avant de l'accepter. À quel moment du projet auriez-vous dû anticiper ces exigences techniques ?",
    answer: ["dès le montage", "au montage", "pendant le montage", "des le montage"], points: 2 },
  { id: "q013", type: "mcq", text: "Une chaîne vous explique qu'elle réserve un créneau horaire fixe chaque semaine aux documentaires. Comment appelle-t-on ce créneau régulier ?",
    options: ["Une case de programmation", "Un préachat", "Une ligne éditoriale", "Un PAD"],
    answer: "Une case de programmation", points: 1 },
  { id: "q014", type: "mcq", text: "Votre documentaire a raté sa diffusion en direct, mais les spectateurs peuvent encore le voir en ligne dans les jours qui suivent. Comment appelle-t-on ce service ?",
    options: ["Le catch-up TV / replay", "Le PAD", "Le préachat", "La case de programmation"],
    answer: "Le catch-up TV / replay", points: 1 },
  { id: "q015", type: "mcq", text: "Une chaîne comme Arte, avec des cases documentaires identifiées et des obligations culturelles, correspond à quelle famille de diffuseurs ?",
    options: ["Publique", "Privée gratuite", "Payante / thématique", "Plateforme numérique"],
    answer: "Publique", points: 1 },
  { id: "q016", type: "mcq", text: "Une chaîne thématique qui cherche des documentaires rares ou exclusifs pour un public déjà ciblé correspond à quelle famille de diffuseurs ?",
    options: ["Publique", "Privée gratuite", "Payante / thématique", "FAST"],
    answer: "Payante / thématique", points: 2 },
  { id: "q017", type: "mcq", text: "Avant de contacter une chaîne pour lui proposer votre documentaire, quelle information est la plus utile à rechercher en priorité ?",
    options: ["Sa ligne éditoriale et les sujets qu'elle a déjà diffusés", "Le nom de son standard téléphonique", "Le nombre total de salariés de la chaîne", "Son adresse postale"],
    answer: "Sa ligne éditoriale et les sujets qu'elle a déjà diffusés", points: 2 },

  // ============================================================
  // 3. Plateformes numériques
  // ============================================================
  { id: "q018", type: "mcq", text: "Une plateforme fait payer à ses utilisateurs un abonnement chaque mois pour accéder à tout son catalogue de films, comme Netflix. Quel modèle est-ce ?",
    options: ["SVOD", "TVOD", "AVOD", "FAST"],
    answer: "SVOD", points: 1 },
  { id: "q019", type: "mcq", text: "Un spectateur paie une seule fois pour louer ou acheter votre documentaire, sans abonnement. Quel modèle est-ce ?",
    options: ["SVOD", "TVOD", "AVOD", "FVOD"],
    answer: "TVOD", points: 1 },
  { id: "q020", type: "mcq", text: "Une plateforme comme YouTube diffuse gratuitement votre film, financée par la publicité affichée avant ou pendant la vidéo. Quel modèle est-ce ?",
    options: ["SVOD", "AVOD", "FVOD", "FAST"],
    answer: "AVOD", points: 1 },
  { id: "q021", type: "mcq", text: "Une médiathèque propose votre documentaire gratuitement, sans aucune publicité. Quel modèle est-ce ?",
    options: ["AVOD", "FVOD", "FAST", "TVOD"],
    answer: "FVOD", points: 1 },
  { id: "q022", type: "mcq", text: "Une box connectée propose des chaînes gratuites diffusées en direct, financées par la publicité. Quel modèle est-ce ?",
    options: ["SVOD", "AVOD", "FAST", "FVOD"],
    answer: "FAST", points: 1 },
  { id: "q023", type: "text", text: "Sur une plateforme, votre film risque de se retrouver noyé parmi des milliers d'autres titres, sans que personne ne le découvre. Comment appelle-t-on l'ensemble des films disponibles à un moment donné sur une plateforme ?",
    answer: ["catalogue"], points: 2 },
  { id: "q024", type: "mcq", text: "Comparé à une sortie en salle, une sortie sur plateforme offre généralement :",
    options: ["Un coût de sortie plus élevé mais une visibilité plus courte", "Un coût de sortie plus faible mais une visibilité plus longue dans le temps", "Une rémunération toujours plus claire", "Un accompagnement presse plus important qu'en salle"],
    answer: "Un coût de sortie plus faible mais une visibilité plus longue dans le temps", points: 2 },
  { id: "q025", type: "mcq", text: "Une limite fréquemment citée des plateformes, par rapport à une sortie en salle, est :",
    options: ["Le manque d'accompagnement presse", "Le coût très élevé des copies", "L'absence totale de public", "L'impossibilité de toucher un public international"],
    answer: "Le manque d'accompagnement presse", points: 2 },
  { id: "q026", type: "mcq", text: "Comparée à une sortie en salle, la rémunération d'une sortie plateforme est généralement présentée comme :",
    options: ["Toujours plus élevée", "Souvent moins transparente", "Généralement fixée à l'avance par contrat", "Fixée par la loi"],
    answer: "Souvent moins transparente", points: 2 },

  // ============================================================
  // 4. Le dossier de présentation type
  // ============================================================
  { id: "q027", type: "text", text: "Vous préparez le dossier qui présentera votre projet à un producteur ou une commission de financement. Citez un des 5 documents clés qu'il doit contenir.",
    answer: ["résumé", "resume", "note d'intention", "note d intention", "synopsis développé", "synopsis developpe", "synopsis", "note de réalisation", "note de realisation", "biographie", "filmographie"], points: 2 },
  { id: "q028", type: "mcq", text: "Dans votre note d'intention, vous expliquez pourquoi ce sujet vous touche personnellement et comment vous l'avez découvert. Pouvez-vous y écrire « je » ?",
    options: ["Non, seul le producteur peut employer le « je »", "Oui, la note d'intention parle de vous et de votre motivation", "Seulement dans la biographie", "Seulement si le film est autobiographique"],
    answer: "Oui, la note d'intention parle de vous et de votre motivation", points: 1 },
  { id: "q029", type: "mcq", text: "Dans le synopsis développé de votre dossier, vous devez avant tout :",
    options: ["Parler de vous et de votre parcours personnel", "Décrire ce que le spectateur va voir et ressentir, avec un vocabulaire simple", "Détailler le budget du film", "Lister votre filmographie complète"],
    answer: "Décrire ce que le spectateur va voir et ressentir, avec un vocabulaire simple", points: 2 },
  { id: "q030", type: "mcq", text: "Vous hésitez à raconter, dans votre note d'intention, le chemin personnel qui vous a mené vers ce sujet plutôt que de rester neutre et descriptif. Que recommande le cours ?",
    options: ["Rester neutre : le parcours personnel n'a pas sa place dans ce document", "Raconter ce chemin : c'est cette sincérité qui fait la force d'une bonne note d'intention", "Réserver ce type de récit à la biographie uniquement", "Ce choix n'a aucune importance pour un producteur"],
    answer: "Raconter ce chemin : c'est cette sincérité qui fait la force d'une bonne note d'intention", points: 2 },
  { id: "q031", type: "text", text: "Vous voulez vous entraîner à écrire un dossier de présentation en consultant des dossiers de films déjà réalisés, gratuitement et en ligne. Quelle ressource le cours recommande-t-il pour ça ?",
    answer: ["scénariothèque", "scenariotheque", "scénariothèque du cnc", "scenariotheque du cnc", "cnc", "la scénariothèque du cnc"], points: 2 },
  { id: "q032", type: "mcq", text: "Dans votre dossier de présentation, un producteur lit votre biographie juste après votre synopsis et votre note d'intention. Que doit-elle apporter à ce stade, selon le cours ?",
    options: ["Une liste exhaustive de tous vos emplois passés", "Un éclairage sur votre parcours et votre légitimité à raconter ce sujet précis", "Un résumé du budget prévisionnel du film", "Des détails sur votre vie privée sans lien avec le film"],
    answer: "Un éclairage sur votre parcours et votre légitimité à raconter ce sujet précis", points: 2 },
  { id: "q033", type: "mcq", text: "Un lecteur professionnel (producteur, commission) reçoit votre dossier de présentation. Selon le cours, en combien de temps doit-il pouvoir situer chaque document du dossier ?",
    options: ["En quelques secondes", "En une heure", "Après avoir vu le film entier", "Jamais avant le tournage"],
    answer: "En quelques secondes", points: 1 },
  { id: "q034", type: "text", text: "La note de réalisation et la note d'intention sont souvent confondues. La note de réalisation explique comment vous allez faire le film plutôt que pourquoi. Combien de pages maximum le cours recommande-t-il pour chacune de ces deux notes ?",
    answer: ["1-2 pages", "1 à 2 pages", "1-2", "une a deux pages", "1 a 2 pages"], points: 2 },

  // ============================================================
  // 5. Logline et synopsis
  // ============================================================
  { id: "q035", type: "mcq", text: "Une logline efficace doit avant tout :",
    options: ["Résumer neutralement toute l'intrigue du film", "Donner envie d'en savoir plus, sans tout expliquer", "Lister tous les personnages du film", "Faire au moins une demi-page"],
    answer: "Donner envie d'en savoir plus, sans tout expliquer", points: 2 },
  { id: "q036", type: "mcq", text: "Une logline efficace contient généralement :",
    options: ["Le budget et le calendrier de tournage", "Le sujet, un personnage central, une tension, et ce qui rend le projet unique", "La biographie complète du réalisateur", "La liste des festivals visés"],
    answer: "Le sujet, un personnage central, une tension, et ce qui rend le projet unique", points: 2 },
  { id: "q037", type: "text", text: "Vous construisez votre logline en trois temps : vous présentez d'abord qui est au cœur du film, puis ce que le film explore à travers cette personne, puis la question qu'il pose. Comment appelle-t-on ce premier élément, celui qui ouvre la logline ?",
    answer: ["personnage", "le personnage", "personnage/groupe", "le personnage ou le groupe", "un personnage"], points: 2 },
  { id: "q038", type: "mcq", text: "Vous devez envoyer un résumé de quelques lignes à une demi-page pour un catalogue de festival, clair et précis. Quel type de document rédigez-vous ?",
    options: ["Un synopsis court", "Un synopsis long", "Une note de réalisation", "Un dossier de presse complet"],
    answer: "Un synopsis court", points: 1 },
  { id: "q039", type: "mcq", text: "Un synopsis long, contrairement au synopsis court, doit surtout :",
    options: ["Tenir en une seule phrase", "Développer le contexte, les personnages et la progression de l'histoire, sans parler de l'auteur", "Parler principalement de vous et de votre parcours", "Remplacer entièrement la note d'intention"],
    answer: "Développer le contexte, les personnages et la progression de l'histoire, sans parler de l'auteur", points: 2 },
  { id: "q040", type: "mcq", text: "Lequel de ces deux synopsis est le plus précis, selon la méthode du cours : « Un documentaire sur le monde du travail aujourd'hui » ou « Dans un entrepôt logistique de la banlieue lyonnaise, trois caristes de nuit tentent d'obtenir un CDI avant la fermeture du site » ?",
    options: ["Le premier, car il évite de trop dévoiler l'histoire", "Le second, car il donne des lieux, personnes et situations précises", "Les deux sont équivalents", "Aucun des deux n'est un synopsis valable"],
    answer: "Le second, car il donne des lieux, personnes et situations précises", points: 2 },
  { id: "q041", type: "text", text: "Votre dossier de présentation risque de se perdre parmi des centaines d'autres si votre synopsis reste flou et général. Quel est le principal défaut à éviter, selon le cours ?",
    answer: ["manque de précision", "le manque de précision", "être trop vague", "trop vague", "imprécision"], points: 2 },
  { id: "q042", type: "mcq", text: "Le cours distingue le pitch, la logline et le synopsis. Le pitch désigne :",
    options: ["Un document juridique", "Une présentation orale ou écrite très courte de votre projet", "Uniquement le budget du film", "La bande-annonce finale"],
    answer: "Une présentation orale ou écrite très courte de votre projet", points: 1 },

  // ============================================================
  // 6. Note d'intention et note de réalisation
  // ============================================================
  { id: "q043", type: "text", text: "Vous choisissez délibérément de filmer votre sujet caméra à l'épaule, sans interview face caméra, pour créer une proximité particulière avec les personnes filmées. Comment appelle-t-on ce choix assumé de style et de point de vue ?",
    answer: ["parti pris", "un parti pris"], points: 2 },
  { id: "q044", type: "mcq", text: "Le « dispositif filmique » d'un documentaire désigne :",
    options: ["Le budget technique du tournage", "La façon d'organiser la relation entre la caméra, le réalisateur et les personnes filmées", "La liste des équipements utilisés", "Le montage final du film"],
    answer: "La façon d'organiser la relation entre la caméra, le réalisateur et les personnes filmées", points: 2 },
  { id: "q045", type: "mcq", text: "Vous décidez de raconter votre sujet du point de vue des enfants plutôt que des adultes. Comment appelle-t-on ce point de vue précis choisi pour aborder un sujet ?",
    options: ["Un angle d'attaque", "Un dispositif filmique", "Un parti pris technique", "Une note de production"],
    answer: "Un angle d'attaque", points: 2 },
  { id: "q046", type: "mcq", text: "Dans votre note de réalisation, vous devez répondre à la question : « Utiliserai-je de la voix off, des archives, de la musique ? ». Cette question relève de :",
    options: ["La note d'intention", "La note de réalisation", "La note de production", "Le synopsis court"],
    answer: "La note de réalisation", points: 1 },
  { id: "q047", type: "mcq", text: "Contrairement à la note de réalisation, la note d'intention doit répondre à la question :",
    options: ["Comment raconter cette histoire ?", "Quel dispositif de mise en scène choisir ?", "Pourquoi ce documentaire, quel est mon angle et mon parti pris ?", "Voix off ou archives ?"],
    answer: "Pourquoi ce documentaire, quel est mon angle et mon parti pris ?", points: 2 },
  { id: "q048", type: "mcq", text: "Selon le cours, la note d'intention et la note de réalisation sont souvent difficiles à écrire parce que :",
    options: ["Elles demandent des connaissances juridiques", "Elles demandent de se dévoiler, contrairement à un document purement technique", "Elles doivent être rédigées en anglais", "Elles sont réservées aux films institutionnels"],
    answer: "Elles demandent de se dévoiler, contrairement à un document purement technique", points: 2 },
  { id: "q049", type: "text", text: "Un bon dispositif filmique doit se décrire comment, selon le cours ?",
    answer: ["avec des choix précis", "choix précis", "des choix précis, pas des généralités", "de facon precise"], points: 2 },

  // ============================================================
  // 7. Le dossier de presse professionnel (EPK)
  // ============================================================
  { id: "q050", type: "mcq", text: "Un journaliste vous demande votre dossier de presse pour préparer un article sur votre film. À qui s'adresse principalement ce document ?",
    options: ["Aux financeurs du film", "Aux journalistes", "Aux commissions d'aide", "Au grand public directement"],
    answer: "Aux journalistes", points: 1 },
  { id: "q051", type: "text", text: "Vous construisez le plan de votre dossier de presse en suivant la structure standard vue en cours, qui comporte 9 parties distinctes. Citez l'une de ces parties.",
    answer: ["couverture", "fiche technique", "générique", "generique", "synopsis", "note d'intention", "note d intention", "note de production", "entretien", "biographie", "filmographie", "visuels", "contacts"], points: 2 },
  { id: "q052", type: "mcq", text: "Vous envoyez à un journaliste un document qui mélange votre dossier artistique destiné aux financeurs et votre dossier de presse. Quelle erreur fréquente commettez-vous ?",
    options: ["Le manque de crédits photographiques uniquement", "Le mélange dossier artistique / dossier presse, à éviter absolument", "L'oubli de la fiche technique", "Un synopsis trop court"],
    answer: "Le mélange dossier artistique / dossier presse, à éviter absolument", points: 2 },
  { id: "q053", type: "mcq", text: "Votre film vise une circulation internationale. Dans quelle(s) langue(s) le cours recommande-t-il de rédiger le dossier de presse ?",
    options: ["Uniquement en français", "Uniquement en anglais", "En français ET en anglais", "Peu importe la langue"],
    answer: "En français ET en anglais", points: 2 },
  { id: "q054", type: "mcq", text: "Dans l'entretien avec le réalisateur inclus dans le dossier de presse, un journaliste attend surtout :",
    options: ["Des explications techniques longues et détaillées", "Des réponses courtes et incarnées, avec un ton naturel", "Une répétition de la note d'intention", "Un résumé complet du budget"],
    answer: "Des réponses courtes et incarnées, avec un ton naturel", points: 2 },
  { id: "q055", type: "text", text: "Vous publiez une photo de tournage dans votre dossier de presse sans mentionner le nom du photographe. Quel élément obligatoire avez-vous oublié ?",
    answer: ["crédit photographique", "le crédit photographique", "crédit", "credit photographique", "credit"], points: 2 },
  { id: "q056", type: "mcq", text: "La fiche technique d'un dossier de presse doit contenir des informations précises comme :",
    options: ["La durée, le format, la langue, le pays", "Le prix de vente du film", "Les coordonnées bancaires du producteur", "La liste des critiques reçues"],
    answer: "La durée, le format, la langue, le pays", points: 1 },
  { id: "q057", type: "mcq", text: "Le générique, dans un dossier de presse, désigne :",
    options: ["Le résumé du film", "La liste des personnes ayant travaillé sur le film", "La fiche technique", "Le contact presse"],
    answer: "La liste des personnes ayant travaillé sur le film", points: 1 },
  { id: "q058", type: "mcq", text: "Une photo utilisable par les journalistes dans leurs articles, fournie dans votre dossier de presse, s'appelle :",
    options: ["Un visuel presse", "Un générique", "Une fiche technique", "Une spotting list"],
    answer: "Un visuel presse", points: 1 },

  // ============================================================
  // 8. Évaluer les effets du documentaire sur le public
  // ============================================================
  { id: "q059", type: "mcq", text: "Votre documentaire est vu par peu de spectateurs, mais il change durablement une pratique professionnelle dans le secteur qu'il aborde. Que peut-on dire ?",
    options: ["Le film a une faible audience mais peut avoir un impact fort", "Le film a forcément échoué", "L'audience et l'impact sont toujours proportionnels", "Le film a raté sa case de programmation"],
    answer: "Le film a une faible audience mais peut avoir un impact fort", points: 2 },
  { id: "q060", type: "mcq", text: "Compter le nombre de personnes ayant vu votre film à sa sortie correspond à mesurer :",
    options: ["L'impact", "L'audience", "La ligne éditoriale", "Le potentiel de circulation"],
    answer: "L'audience", points: 1 },
  { id: "q061", type: "mcq", text: "Votre documentaire sur la disparition de migrants en mer inspire une campagne de sensibilisation qui se poursuit bien après sa diffusion, avec des projections-débats et des relais associatifs. Quel type d'impact cela illustre-t-il en premier lieu ?",
    options: ["Impact médiatique uniquement", "Impact public et institutionnel", "Impact esthétique uniquement", "Impact purement financier"],
    answer: "Impact public et institutionnel", points: 2 },
  { id: "q062", type: "text", text: "Votre documentaire est repris dans des articles et interviews sur plusieurs médias après sa sortie. Quel type d'impact cela illustre-t-il ?",
    answer: ["médiatique", "impact médiatique", "mediatique", "impact mediatique"], points: 1 },
  { id: "q063", type: "mcq", text: "Votre documentaire est intégré dans des programmes scolaires et fait l'objet de débats politiques sur son sujet. Quels types d'impact cela combine-t-il ?",
    options: ["Médiatique et industriel", "Politique et éducatif", "Audience et exploitation", "Distribution et diffusion"],
    answer: "Politique et éducatif", points: 2 },
  { id: "q064", type: "text", text: "Vous voulez suivre concrètement l'impact de votre documentaire après sa sortie, au-delà de vos impressions personnelles. Citez une des méthodes concrètes vues en cours pour l'observer.",
    answer: ["questionnaire de sortie", "veille presse", "veille réseaux", "veille reseaux", "comptage", "témoignages", "temoignages", "demandes de projection"], points: 2 },
  { id: "q065", type: "mcq", text: "Vous remettez au public quelques questions courtes juste après la projection de votre film. Quelle méthode d'observation de l'impact utilisez-vous ?",
    options: ["Le questionnaire de sortie", "La veille presse", "Le comptage des demandes de projection", "La reddition de comptes"],
    answer: "Le questionnaire de sortie", points: 1 },
  { id: "q066", type: "mcq", text: "Selon le cours, pourquoi vaut-il mieux mettre en place des outils d'observation de l'impact dès la sortie du film, plutôt que d'attendre ?",
    options: ["Ce n'est pas nécessaire, l'intuition suffit", "Sans ces outils, on ne garde souvent que des impressions vagues, difficiles à réutiliser", "La loi l'exige formellement", "Cela coûte moins cher après coup"],
    answer: "Sans ces outils, on ne garde souvent que des impressions vagues, difficiles à réutiliser", points: 2 },

  // ============================================================
  // 9. Analyser réception, controverses et points forts
  // ============================================================
  { id: "q067", type: "mcq", text: "Une critique salue la qualité de l'image et du montage de votre documentaire, sans parler de son sujet ni de sa place sur le marché. Quel niveau de lecture cette critique utilise-t-elle ?",
    options: ["Esthétique", "Politique", "Industriel", "Médiatique"],
    answer: "Esthétique", points: 1 },
  { id: "q068", type: "mcq", text: "Une critique compare votre documentaire à d'autres sorties récentes et évoque sa place sur le marché du documentaire. Quel niveau de lecture est-ce ?",
    options: ["Esthétique", "Politique", "Industriel", "Public"],
    answer: "Industriel", points: 1 },
  { id: "q069", type: "mcq", text: "Une critique commente ce que votre film dit du monde et le point de vue qu'il défend sur son sujet. Quel niveau de lecture est-ce ?",
    options: ["Esthétique", "Politique", "Industriel", "Médiatique"],
    answer: "Politique", points: 1 },
  { id: "q070", type: "mcq", text: "Une critique salue votre mise en scène tout en étant très sévère sur le point de vue politique défendu par le film, dans le même article. Que révèle cette situation, selon le cours ?",
    options: ["Une erreur d'analyse du critique", "Le mélange fréquent de plusieurs niveaux de lecture dans un même article", "Un cas impossible en pratique", "Une controverse automatique"],
    answer: "Le mélange fréquent de plusieurs niveaux de lecture dans un même article", points: 2 },
  { id: "q071", type: "mcq", text: "Un article pointe un problème précis sur une scène de votre film, puis d'autres médias reprennent le sujet en l'amplifiant. Quelle est l'étape suivante typique du circuit d'une controverse, selon le cours ?",
    options: ["Le sujet disparaît immédiatement", "La réaction du réalisateur ou du producteur", "Un procès automatique", "Le retrait du film de tous les circuits"],
    answer: "La réaction du réalisateur ou du producteur", points: 2 },
  { id: "q072", type: "text", text: "Selon le circuit type d'une controverse, qu'est-ce qui déclenche généralement la toute première étape ?",
    answer: ["un article", "un post", "un detail precis", "un détail précis", "une scene", "une scène", "une déclaration en interview", "une declaration en interview"], points: 2 },
  { id: "q073", type: "mcq", text: "Une seule critique mentionne un point fort de votre film ; aucune autre ne le reprend. Comment devez-vous considérer ce point, selon la méthode vue en cours ?",
    options: ["Comme un vrai point fort à mettre en avant partout", "Comme un avis isolé, pas encore une tendance de réception confirmée", "Comme une erreur du critique à corriger", "Comme une controverse naissante"],
    answer: "Comme un avis isolé, pas encore une tendance de réception confirmée", points: 2 },
  { id: "q074", type: "mcq", text: "Pour identifier les vrais points forts de votre film à partir de plusieurs critiques indépendantes, la méthode du cours consiste à :",
    options: ["Ne garder que l'avis du critique le plus connu", "Chercher les répétitions entre les différentes critiques lues", "Faire la moyenne des notes attribuées", "Ignorer les critiques négatives"],
    answer: "Chercher les répétitions entre les différentes critiques lues", points: 2 },
  { id: "q075", type: "mcq", text: "Un article de presse qui donne un avis professionnel sur votre film s'appelle :",
    options: ["Une critique de presse", "Un dossier de presse", "Un communiqué", "Une note de production"],
    answer: "Une critique de presse", points: 1 },

  // ============================================================
  // 10. Monter un plan de circulation du film
  // ============================================================
  { id: "q076", type: "mcq", text: "Votre film a déjà été mis en ligne il y a 2 mois lorsque vous candidatez à un grand festival exigeant une première mondiale. Que risque votre candidature ?",
    options: ["Le festival exige simplement une nouvelle bande-annonce", "Le festival peut refuser votre film car la première mondiale n'est plus possible", "Le festival vous accorde automatiquement une dérogation", "Cela n'affecte que les festivals régionaux"],
    answer: "Le festival peut refuser votre film car la première mondiale n'est plus possible", points: 2 },
  { id: "q077", type: "text", text: "Un festival vous demande de préciser si votre film aura sa toute première projection publique mondiale chez eux. Comment appelle-t-on ce type de première ?",
    answer: ["première mondiale", "premiere mondiale"], points: 1 },
  { id: "q078", type: "mcq", text: "Vous organisez le circuit de votre film dans un ordre logique plutôt que d'envoyer à tous les festivals en même temps. Quelle est la première étape de ce circuit hiérarchisé ?",
    options: ["Les festivals régionaux", "Le festival de lancement (première)", "Les festivals spécialisés", "L'envoi simultané à tous les festivals"],
    answer: "Le festival de lancement (première)", points: 2 },
  { id: "q079", type: "mcq", text: "Dans un circuit hiérarchisé bien construit, à quel moment viennent les festivals régionaux ?",
    options: ["En tout premier", "Juste après le festival de lancement", "En dernier, après les festivals internationaux et spécialisés", "Ils ne font jamais partie du circuit"],
    answer: "En dernier, après les festivals internationaux et spécialisés", points: 2 },
  { id: "q080", type: "mcq", text: "Un festival annonce que les dossiers doivent être envoyés au plus tard le 15 mars. Quel mot désigne cette date limite ?",
    options: ["Une deadline", "Un holdback", "Une exclusivité", "Un rétroplanning"],
    answer: "Une deadline", points: 1 },
  { id: "q081", type: "text", text: "Vous construisez un calendrier pour suivre vos candidatures à plusieurs festivals. En plus du nom du festival et de la deadline de dépôt, quel autre élément ce calendrier doit-il suivre pour être vraiment utile ?",
    answer: ["le statut de la candidature", "statut de la candidature", "le statut", "la date de réponse attendue", "date de réponse", "date de reponse"], points: 2 },
  { id: "q082", type: "mcq", text: "Selon le cours, une stratégie professionnelle de circulation en festivals privilégie :",
    options: ["Un envoi simultané à tous les festivals possibles", "Un circuit hiérarchisé pensé avant la fin du montage", "Un envoi uniquement après la fin complète du montage", "L'absence totale de planification"],
    answer: "Un circuit hiérarchisé pensé avant la fin du montage", points: 2 },
  { id: "q083", type: "mcq", text: "Sans calendrier de deadlines réelles, quel risque concret le cours met-il en avant ?",
    options: ["Devoir renégocier le mandat de distribution", "Découvrir une deadline dépassée au pire moment", "Recevoir trop de réponses positives", "Payer des frais de dépôt plus élevés"],
    answer: "Découvrir une deadline dépassée au pire moment", points: 1 },

  // ============================================================
  // 11. Savoir présenter son film aux bons interlocuteurs
  // ============================================================
  { id: "q084", type: "mcq", text: "Qui, dans la chaîne du documentaire, gère l'argent et l'organisation du film dès l'écriture ou le développement ?",
    options: ["Le producteur", "Le distributeur", "Le vendeur international", "Le diffuseur"],
    answer: "Le producteur", points: 1 },
  { id: "q085", type: "mcq", text: "Qui intervient après le producteur pour faire circuler le film une fois prêt : salle, festivals, VOD, presse ?",
    options: ["Le producteur", "Le distributeur", "L'auteur", "Le mandant"],
    answer: "Le distributeur", points: 1 },
  { id: "q086", type: "mcq", text: "Vous rencontrez Sophie Marchal, productrice indépendante, qui vous dit chercher des projets avec un vrai point de vue d'auteur et s'intéresser autant au dispositif de tournage qu'au sujet. Quel angle privilégier dans votre présentation ?",
    options: ["Le potentiel de circulation et le public visé", "Le désir de film, le sujet et le dispositif", "Le prix de vente du film", "La liste des festivals déjà visés"],
    answer: "Le désir de film, le sujet et le dispositif", points: 2 },
  { id: "q087", type: "mcq", text: "Vous rencontrez Karim Belaïd, distributeur indépendant, qui vous demande si votre film peut remplir une salle un samedi soir et s'il y a un public identifiable. Quel angle privilégier face à lui ?",
    options: ["Le dispositif artistique du tournage", "Le public visé et le potentiel de circulation", "Votre biographie personnelle", "Le droit moral de l'auteur"],
    answer: "Le public visé et le potentiel de circulation", points: 2 },
  { id: "q088", type: "mcq", text: "Vous signez un mandat de distribution avec la société Marée Haute Distribution pour votre film. Le contrat lui confie l'exploitation exclusive sur le territoire suivant : France métropolitaine et Belgique uniquement, pour une durée de 3 ans. Un distributeur japonais vous contacte ensuite pour exploiter le film chez lui. Pouvez-vous signer avec lui sans l'accord de Marée Haute Distribution ?",
    options: ["Oui, le mandat ne couvre pas le Japon donc vous êtes libre sur ce territoire", "Non, il faut son accord même en dehors de son territoire", "Oui, mais seulement après la fin du mandat", "Non, aucune vente internationale n'est jamais possible"],
    answer: "Oui, le mandat ne couvre pas le Japon donc vous êtes libre sur ce territoire", points: 2 },
  { id: "q089", type: "text", text: "Dans un mandat de distribution, le distributeur vous verse à la signature un minimum garanti de 5 000 €, remboursé sur les futures recettes du film. Une fois ce minimum garanti intégralement remboursé, il garde ensuite 30 % des recettes nettes. Le film génère par la suite 20 000 € de recettes nettes après ce remboursement. Combien revient-il au producteur sur cette somme ?",
    answer: ["14000", "14000€", "14000 €", "14 000", "14 000€", "14 000 €"], points: 2 },
  { id: "q090", type: "mcq", text: "Dans un mandat de distribution, les frais de promotion et de sortie engagés par le distributeur (copies, matériel publicitaire, relations presse) sont plafonnés contractuellement à 6 000 €. Pourquoi ce plafond protège-t-il les intérêts du producteur ?",
    options: ["Il augmente automatiquement les recettes du film", "Sans lui, ces frais pourraient gonfler et retarder le moment où le producteur touche de l'argent", "Il rend le contrat plus long à négocier", "Il supprime toute obligation de reporting du distributeur"],
    answer: "Sans lui, ces frais pourraient gonfler et retarder le moment où le producteur touche de l'argent", points: 2 },
  { id: "q091", type: "text", text: "Dans un mandat de distribution, le contrat prévoit que le distributeur transmette au producteur un relevé détaillé des recettes tous les 4 mois, plutôt que seulement à la fin du mandat. Comment appelle-t-on ce relevé périodique, dans le vocabulaire du cours ?",
    answer: ["reddition de comptes", "la reddition de comptes", "reddition des comptes", "une reddition de comptes"], points: 2 },
  { id: "q092", type: "mcq", text: "Dans un mandat de distribution, il est prévu qu'en cas de manquement grave de l'une des parties (par exemple, une reddition de comptes jamais transmise malgré plusieurs relances), l'autre partie peut résilier le contrat, mais seulement après :",
    options: ["Une décision immédiate sans préavis", "Une mise en demeure restée sans effet pendant un délai précis fixé au contrat", "L'accord d'un vendeur international", "Le remboursement intégral du minimum garanti"],
    answer: "Une mise en demeure restée sans effet pendant un délai précis fixé au contrat", points: 2 },
  { id: "q093", type: "mcq", text: "La personne à qui vous vous adressez pour faire avancer votre projet (producteur, distributeur...) s'appelle, dans le vocabulaire du cours :",
    options: ["Un interlocuteur", "Un mandant", "Un mandataire", "Un ayant droit"],
    answer: "Un interlocuteur", points: 1 },

  // ============================================================
  // 12. Créer une bande-annonce qui donne envie
  // ============================================================
  { id: "q094", type: "mcq", text: "Votre film n'est pas encore terminé, mais vous voulez créer de la curiosité autour de lui sans tout dévoiler. Quel outil utiliser ?",
    options: ["Le teaser", "La bande-annonce", "Le dossier de presse", "La note de réalisation"],
    answer: "Le teaser", points: 1 },
  { id: "q095", type: "mcq", text: "Votre film est presque terminé et vous voulez le promouvoir auprès du public en présentant son sujet, ses personnages et sa tension. Quel outil utiliser ?",
    options: ["Le teaser", "La bande-annonce", "La note d'intention", "Le synopsis court"],
    answer: "La bande-annonce", points: 1 },
  { id: "q096", type: "text", text: "Vous montez un teaser pour présenter votre projet à un producteur avant même que le film soit terminé, en suivant la structure en plusieurs éléments recommandée en cours. Citez l'un de ces éléments.",
    answer: ["accroche", "situation", "tension", "personnage", "voix", "promesse", "titre", "sélection", "selection", "prix"], points: 2 },
  { id: "q097", type: "mcq", text: "Un teaser efficace, selon le cours, doit surtout :",
    options: ["Expliquer entièrement l'intrigue du film", "Jouer sur la suggestion plutôt que l'explication, pour donner envie d'en savoir plus", "Durer au minimum 3 minutes", "Éviter toute musique ou son"],
    answer: "Jouer sur la suggestion plutôt que l'explication, pour donner envie d'en savoir plus", points: 2 },
  { id: "q098", type: "mcq", text: "Selon le cours, un teaser peut aussi servir à :",
    options: ["Remplacer entièrement le dossier de presse", "Convaincre un producteur ou un financeur avant même que le film soit terminé", "Signer un mandat de distribution", "Fixer le prix plancher de négociation"],
    answer: "Convaincre un producteur ou un financeur avant même que le film soit terminé", points: 2 },
  { id: "q099", type: "text", text: "Le dernier élément (optionnel) de la structure d'un teaser efficace consiste à mentionner une reconnaissance déjà obtenue par le projet. De quoi s'agit-il ?",
    answer: ["sélection", "selection", "prix", "mention de sélection", "mention de selection", "mention de sélection ou prix"], points: 2 },
  { id: "q100", type: "mcq", text: "Quelle est la durée approximative d'une bande-annonce, selon le vocabulaire du cours ?",
    options: ["30 secondes à 1 minute 30", "1 minute 30 à 2 minutes 30", "5 à 10 minutes", "3 à 5 minutes"],
    answer: "1 minute 30 à 2 minutes 30", points: 1 },

  // ============================================================
  // 13. Déployer une communication cohérente autour du film
  // ============================================================
  { id: "q101", type: "text", text: "Vous montez le plan de communication de votre film et devez choisir parmi les différents outils vus en cours. Citez l'un de ces outils.",
    answer: ["réseaux sociaux", "reseaux sociaux", "mailing", "relais", "site web", "site web / blog", "blog"], points: 1 },
  { id: "q102", type: "mcq", text: "Vous constituez une liste de contacts presse et partenaires à qui envoyer régulièrement des informations sur votre film. Quel outil utilisez-vous ?",
    options: ["Le mailing", "Le relais", "Les réseaux sociaux", "Le calendrier éditorial"],
    answer: "Le mailing", points: 1 },
  { id: "q103", type: "mcq", text: "Une association locale accepte de partager votre film à son propre public, en plus de votre communication directe. Comment appelle-t-on ce type de partenaire ?",
    options: ["Un relais", "Un mailing", "Un diffuseur", "Un vendeur international"],
    answer: "Un relais", points: 1 },
  { id: "q104", type: "mcq", text: "Vous publiez le même contenu presse et le même contenu réseaux sociaux la même semaine, sans les distinguer, juste avant votre sortie. Quel principe du cours violez-vous ?",
    options: ["Le principe du prix plancher", "La presse a besoin d'un délai avant la publication publique", "Le principe de windowing", "Le droit moral"],
    answer: "La presse a besoin d'un délai avant la publication publique", points: 2 },
  { id: "q105", type: "mcq", text: "Vous construisez le calendrier éditorial de sortie de votre film : les publications sont rares 3 mois avant la sortie, se multiplient dans les deux dernières semaines, puis se poursuivent encore quelques semaines après J0. Quel principe du cours cette progression illustre-t-elle ?",
    options: ["Un rythme de publication qui augmente progressivement, puis se maintient après la sortie", "Un rythme constant du début à la fin", "Un rythme qui diminue à l'approche de la sortie", "Un arrêt total des publications dès J0"],
    answer: "Un rythme de publication qui augmente progressivement, puis se maintient après la sortie", points: 2 },
  { id: "q106", type: "mcq", text: "Vous préparez le calendrier éditorial de votre film. 8 semaines avant la sortie, vous voulez susciter la curiosité sans encore tout dévoiler. Que publier en priorité à ce moment-là ?",
    options: ["La bande-annonce complète", "Un teaser sur les réseaux sociaux", "Le communiqué de premiers retours", "Les photos de la soirée de première"],
    answer: "Un teaser sur les réseaux sociaux", points: 1 },
  { id: "q107", type: "mcq", text: "Dans le calendrier éditorial de sortie de votre film, 2 semaines après la sortie, les premières critiques commencent à circuler. Que publier sur les réseaux sociaux à ce moment-là pour construire la légitimité du film ?",
    options: ["L'annonce du teaser", "Le partage des critiques reçues", "La bande-annonce complète", "Le premier envoi presse"],
    answer: "Le partage des critiques reçues", points: 2 },
  { id: "q108", type: "mcq", text: "Vous établissez le calendrier éditorial de sortie de votre film. Une erreur fréquente consiste à arrêter toute communication le jour de la sortie (J0). Que recommande le cours de prévoir à la place ?",
    options: ["Ne rien publier après la sortie", "Prévoir 2 à 4 semaines de communication après la sortie pour prolonger la vie du film", "Republier uniquement le teaser initial", "Attendre un an avant de recommuniquer"],
    answer: "Prévoir 2 à 4 semaines de communication après la sortie pour prolonger la vie du film", points: 2 },
  { id: "q109", type: "text", text: "Vous rassemblez dans un seul document votre stratégie et l'ensemble de vos outils de communication (réseaux, mailing, relais). Comment appelle-t-on ce document ?",
    answer: ["plan de communication"], points: 2 },
  { id: "q110", type: "mcq", text: "Le document qui prévoit quoi publier, quand, et sur quel canal, dans les semaines précédant votre sortie, s'appelle :",
    options: ["Un calendrier éditorial", "Un rétroplanning", "Un mandat de distribution", "Un dossier de presse"],
    answer: "Un calendrier éditorial", points: 1 },

  // ============================================================
  // 14. Articuler festivals, médias et projections
  // ============================================================
  { id: "q111", type: "mcq", text: "Après la première de votre film dans un festival, que le cours recommande-t-il de faire démarrer juste après, pour capitaliser sur cette visibilité ?",
    options: ["La campagne presse", "Les projections non-theatrical uniquement", "Le dépôt en festival régional", "La négociation avec un vendeur international"],
    answer: "La campagne presse", points: 2 },
  { id: "q112", type: "mcq", text: "Dans l'enchaînement professionnel typique d'une sortie de film, où se situent les projections publiques et non-theatrical par rapport à la première festival et à la campagne presse ?",
    options: ["Avant la première festival", "En même temps que la première festival", "Après la première festival et la campagne presse", "Immédiatement après le dépôt du dossier au festival"],
    answer: "Après la première festival et la campagne presse", points: 2 },
  { id: "q113", type: "mcq", text: "Pourquoi le cours déconseille-t-il d'actionner festival, presse et projections publiques tous en même temps ?",
    options: ["Cela coûte automatiquement plus cher", "Une sortie mal échelonnée dilue l'attention au lieu de la faire grandir progressivement", "C'est interdit par la loi", "Cela viole systématiquement le droit moral de l'auteur"],
    answer: "Une sortie mal échelonnée dilue l'attention au lieu de la faire grandir progressivement", points: 2 },
  { id: "q114", type: "mcq", text: "Vous devez avoir prêts en même temps votre dossier de presse, votre teaser et vos sous-titres avant une date de sortie fixée. Quel outil de planification est particulièrement utile dans ce cas ?",
    options: ["Le rétroplanning", "Le mandat de distribution", "Le prix plancher", "La spotting list"],
    answer: "Le rétroplanning", points: 2 },
  { id: "q115", type: "text", text: "Contrairement à un calendrier classique qui avance dans le temps, un rétroplanning se construit dans quel sens ?",
    answer: ["en remontant", "en remontant depuis la date de sortie", "à l'envers", "a l'envers", "en partant de la date finale"], points: 2 },
  { id: "q116", type: "mcq", text: "Vous construisez le rétroplanning de sortie de votre film en remontant depuis la date de sortie fixée, et vous décidez de finaliser votre dossier de presse dès la 8ᵉ semaine avant la sortie, bien avant le reste. Pourquoi ce choix est-il pertinent ?",
    options: ["Le dossier de presse n'a aucun lien avec les délais des journalistes", "Les journalistes ont besoin de le recevoir suffisamment tôt pour préparer leurs articles avant la sortie", "C'est une obligation légale sans lien avec la presse", "Cela permet d'éviter de rédiger une note d'intention"],
    answer: "Les journalistes ont besoin de le recevoir suffisamment tôt pour préparer leurs articles avant la sortie", points: 2 },
  { id: "q117", type: "mcq", text: "Un rétroplanning bien construit permet surtout d'éviter :",
    options: ["De payer trop cher les festivals", "D'être pris de court par une échéance mal anticipée", "De devoir écrire une note d'intention", "De signer un mandat de distribution"],
    answer: "D'être pris de court par une échéance mal anticipée", points: 1 },

  // ============================================================
  // 15. Préparer un film circulant sur plusieurs territoires
  // ============================================================
  { id: "q118", type: "mcq", text: "Le fichier final de votre film, livré selon des standards techniques précis, s'appelle :",
    options: ["Le master", "Le mandat", "La spotting list", "Le catalogue"],
    answer: "Le master", points: 1 },
  { id: "q119", type: "mcq", text: "Votre documentaire de 52 minutes doit être proposé à une chaîne TV française (PAD), un festival international (sous-titres anglais obligatoires) et une plateforme SVOD nord-américaine. Combien de versions du master faut-il prévoir au minimum ?",
    options: ["Une seule version suffit pour tous les usages", "Plusieurs versions, adaptées à chaque support et territoire", "Une seule version, mais avec un sous-titrage systématique", "Une seule version, mais en anglais uniquement"],
    answer: "Plusieurs versions, adaptées à chaque support et territoire", points: 2 },
  { id: "q120", type: "mcq", text: "Votre documentaire français vise une circulation internationale : festivals étrangers, diffuseurs non francophones, plateformes hors de France. Quelle langue de sous-titrage constitue la première étape indispensable pour permettre cette circulation ?",
    options: ["Le mandarin", "L'anglais", "L'espagnol", "Le français uniquement"],
    answer: "L'anglais", points: 1 },
  { id: "q121", type: "text", text: "Pour faciliter le travail de traduction de votre film et réduire les erreurs, vous fournissez au traducteur un document listant les dialogues avec leur minutage précis. Comment appelle-t-on ce document ?",
    answer: ["spotting list"], points: 2 },
  { id: "q122", type: "mcq", text: "Le budget et le délai nécessaires à la traduction de votre film doivent être :",
    options: ["Ajoutés au tout dernier moment", "Intégrés dans le calendrier du film dès l'amont", "Ignorés, la traduction est toujours rapide et gratuite", "Négociés uniquement avec le vendeur international"],
    answer: "Intégrés dans le calendrier du film dès l'amont", points: 2 },
  { id: "q123", type: "mcq", text: "Vous voulez faire circuler votre film à l'international et avez besoin de quelqu'un capable de vendre, pays par pays, différents types de droits (TV, plateformes, salle, éducatif). Quel professionnel cherchez-vous ?",
    options: ["Un vendeur international (sales agent)", "Un attaché de presse", "Un distributeur national uniquement", "Un monteur"],
    answer: "Un vendeur international (sales agent)", points: 2 },
  { id: "q124", type: "mcq", text: "Vous avez déjà signé un contrat de distribution nationale pour votre film. Pouvez-vous confier les ventes internationales au même contrat, sans interlocuteur ni contrat distinct ?",
    options: ["Oui, c'est le même contrat qui couvre tout automatiquement", "Non, ce sont deux contrats différents, avec deux interlocuteurs différents", "Oui, mais seulement si le distributeur est d'accord oralement", "Non, les ventes internationales sont toujours interdites"],
    answer: "Non, ce sont deux contrats différents, avec deux interlocuteurs différents", points: 2 },
  { id: "q125", type: "mcq", text: "Faire appel à un vendeur international pour votre film est-il systématique ?",
    options: ["Oui, pour tous les documentaires sans exception", "Non, cela dépend du potentiel de circulation du film", "Oui, mais uniquement pour les films de plus de 90 minutes", "Non, c'est même interdit pour les documentaires"],
    answer: "Non, cela dépend du potentiel de circulation du film", points: 2 },
  { id: "q126", type: "mcq", text: "Une version PAD pour la télévision et une version DCP pour la salle sont deux exemples de :",
    options: ["Contrats différents", "Versions différentes d'un même master", "Erreurs à éviter absolument", "Titres alternatifs du film"],
    answer: "Versions différentes d'un même master", points: 2 },

  // ============================================================
  // 16. Défendre la valeur du film sans le dénaturer (négociation)
  // ============================================================
  { id: "q127", type: "mcq", text: "Avant un rendez-vous de négociation avec un diffuseur, vous fixez à l'avance le montant minimum en dessous duquel vous refuserez de signer, pour ne pas décider sous pression. Comment appelle-t-on ce montant ?",
    options: ["Le prix plancher", "La commission", "Le minimum garanti", "L'argument de valeur"],
    answer: "Le prix plancher", points: 1 },
  { id: "q128", type: "mcq", text: "Un diffuseur vous demande de modifier une scène de votre film contre son avis artistique explicite, en échange d'un meilleur prix. Pouvez-vous négocier ce point ?",
    options: ["Oui, tout se négocie contre un bon prix", "Non, le droit moral et l'intégrité de l'œuvre ne se négocient jamais", "Oui, mais seulement pour les documentaires courts", "Cela dépend uniquement du montant proposé"],
    answer: "Non, le droit moral et l'intégrité de l'œuvre ne se négocient jamais", points: 2 },
  { id: "q129", type: "mcq", text: "Parmi les éléments suivants, lequel est réellement négociable dans une discussion avec un diffuseur ?",
    options: ["Le droit moral de l'auteur", "L'intégrité de l'œuvre", "Le calendrier de livraison", "Le respect de l'œuvre originale"],
    answer: "Le calendrier de livraison", points: 1 },
  { id: "q130", type: "text", text: "Face à un diffuseur hésitant, vous devez construire un argument de valeur solide et vérifiable, comme vu en cours. Citez un type d'argument de ce genre.",
    answer: ["accès exclusif", "acces exclusif", "reconnaissance", "actualité", "actualite"], points: 2 },
  { id: "q131", type: "mcq", text: "Selon le cours, un bon argument de valeur pour convaincre un diffuseur doit s'appuyer sur :",
    options: ["Une conviction personnelle sur la qualité du film", "Un fait vérifiable, comme un accès exclusif ou une reconnaissance déjà reçue", "Le prix payé pour la production", "Le nombre d'heures de tournage"],
    answer: "Un fait vérifiable, comme un accès exclusif ou une reconnaissance déjà reçue", points: 2 },
  { id: "q132", type: "mcq", text: "Vous préparez 10 arguments assez vagues pour votre rendez-vous avec un diffuseur, plutôt que 3 arguments solides et précis. Quel risque le cours met-il en avant ?",
    options: ["Renforcer votre prix plancher", "Diluer votre message et perdre en clarté", "Gagner automatiquement la négociation", "Éviter toute question difficile"],
    answer: "Diluer votre message et perdre en clarté", points: 2 },
  { id: "q133", type: "mcq", text: "Selon le cours, bien négocier signifie :",
    options: ["Céder sur tous les points pour conclure vite", "Refuser tout compromis pour défendre votre position", "Chercher un accord qui respecte les intérêts des deux parties", "Imposer vos conditions sans écouter l'autre partie"],
    answer: "Chercher un accord qui respecte les intérêts des deux parties", points: 2 },
  { id: "q134", type: "mcq", text: "Pour votre film, vous avez obtenu un accès exclusif au tournage des dernières sorties en mer du dernier pêcheur artisanal d'un village. Comment utiliser cet élément face à un diffuseur ?",
    options: ["Le garder secret pour ne pas dévoiler le film", "L'utiliser comme argument de valeur concret pour justifier votre prix", "L'ignorer, ce n'est pas pertinent en négociation", "Le réserver uniquement pour le dossier de presse"],
    answer: "L'utiliser comme argument de valeur concret pour justifier votre prix", points: 2 },
  { id: "q135", type: "text", text: "Comment appelle-t-on l'échange qui vise à trouver un accord entre deux parties aux intérêts différents, par exemple entre un auteur et un diffuseur ?",
    answer: ["négociation", "negociation", "une négociation", "une negociation"], points: 1 },

  // ============================================================
  // 17. Activité de consolidation finale
  // ============================================================
  { id: "q136", type: "mcq", text: "Pour définir le public cible de votre film, la méthode du cours recommande d'imaginer :",
    options: ["Une catégorie abstraite comme « femme, 25-35 ans »", "UNE personne réelle et précise, avec un prénom", "L'ensemble de la population française", "Le profil moyen des spectateurs de festival"],
    answer: "UNE personne réelle et précise, avec un prénom", points: 2 },
  { id: "q137", type: "mcq", text: "Vous avez construit le portrait précis d'un spectateur unique pour votre film, avec un prénom, un âge et des habitudes concrètes, plutôt qu'une catégorie abstraite comme « femme, 25-35 ans ». Quel est l'intérêt réel de cette méthode pour la suite de votre stratégie ?",
    options: ["Aucun, les deux approches se valent strictement", "Elle rend vos choix de circulation et de communication plus concrets et plus faciles à orienter", "Elle sert uniquement à remplir le dossier de presse", "Elle remplace entièrement le besoin d'un plan de communication"],
    answer: "Elle rend vos choix de circulation et de communication plus concrets et plus faciles à orienter", points: 2 },
  { id: "q138", type: "mcq", text: "Selon l'étape « circuit de diffusion » de l'activité de consolidation, comment choisir le circuit principal visé pour votre film ?",
    options: ["Au hasard, tous les circuits se valent", "En repartant du public cible défini à l'étape précédente : où irait-il naturellement voir un film comme le vôtre ?", "En choisissant systématiquement la télévision", "En évitant tout festival"],
    answer: "En repartant du public cible défini à l'étape précédente : où irait-il naturellement voir un film comme le vôtre ?", points: 2 },
  { id: "q139", type: "mcq", text: "Dans l'étape « mon calendrier » de l'activité de consolidation, dans quel ordre les 4 grandes étapes s'enchaînent-elles généralement ?",
    options: ["Projections publiques → première → dépôt festival → campagne presse", "Dépôt festival → première → campagne presse → projections publiques", "Campagne presse → dépôt festival → projections publiques → première", "Il n'y a pas d'ordre recommandé"],
    answer: "Dépôt festival → première → campagne presse → projections publiques", points: 2 },
  { id: "q140", type: "mcq", text: "L'activité de consolidation finale du module vous demande de produire un visuel unique résumant votre démarche. Que recommande le cours à ce sujet ?",
    options: ["Viser un visuel graphiquement parfait, quitte à le laisser inachevé", "Un visuel simple et clair, qu'une personne extérieure peut comprendre en un coup d'œil", "Rédiger un texte long et détaillé plutôt qu'un visuel", "Attendre d'avoir toutes les réponses des diffuseurs avant de le créer"],
    answer: "Un visuel simple et clair, qu'une personne extérieure peut comprendre en un coup d'œil", points: 2 },
];
